### ISSUE TITLE
live-dl failed.

### ISSUE THREAD

**Issue by timmyhbk** [herowinb/live-dl#28]
**Describe the bug**
live-dl failed. Unable to manually/automatically record a livestream.

**To Reproduce**
1. via `nohup bash live-dl` or `auto.sh`.
2. The error

logs (auto.sh)
```
/usr/src/app/live-dl: line 1775: syntax error near unexpected token `}'
/usr/src/app/live-dl: line 1775: `}'
```
logs (nohup bash live-dl...)
```
nohup: ignoring input
live-dl: line 94: cd: live-dl: Not a directory
live-dl: line 1775: syntax error near unexpected token `}'
live-dl: line 1775: `}'
```

**Desktop (please complete the following information):**
 - OS: Docker (Synology NAS)
 - Version: last updated

**Comment by ryan4559** [comment]
#27 PR

**Comment by herowinb** [comment]
Oh i forgot that fi. Many thanks @ryan4559
